### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by jonahfang** [jonahfang/yzcycnproject#214]
File "./apps/ps_stock/views/ship/shiping_detail.py", line 78, in change_my_shiping_detail_amount
Jun 17 11:46:33 iZ23pw03glwZ log.txt:      detail_obj = ShipingDetail.objects.get(id=rid)
Jun 17 11:46:33 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
Jun 17 11:46:33 iZ23pw03glwZ log.txt:      return self.get_query_set().get(*args, **kwargs)
Jun 17 11:46:33 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
Jun 17 11:46:33 iZ23pw03glwZ log.txt:      self.model._meta.object_name)
Jun 17 11:46:33 iZ23pw03glwZ log.txt:  DoesNotExist: ShipingDetail matching query does not exist.

**Comment by jonahfang** [comment]
:  Traceback (most recent call last):
Jun 17 11:46:53 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
Jun 17 11:46:53 iZ23pw03glwZ log.txt:      response = callback(request, *callback_args, **callback_kwargs)
Jun 17 11:46:53 iZ23pw03glwZ log.txt:    File "./apps/utils/resource_base.py", line 184, in __call__
Jun 17 11:46:53 iZ23pw03glwZ log.txt:      return callback()
Jun 17 11:46:53 iZ23pw03glwZ log.txt:    File "./apps/ps_stock/views/ship/shiping_goods.py", line 35, in do_GET
Jun 17 11:46:53 iZ23pw03glwZ log.txt:      return ajax_get(objs[0])
Jun 17 11:46:53 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 231, in __getitem__
Jun 17 11:46:53 iZ23pw03glwZ log.txt:      return list(qs)[0]
Jun 17 11:46:53 iZ23pw03glwZ log.txt:  IndexError: list index out of range
Jun 17 11:46:55 iZ23pw03glwZ log.txt:  [fusion0_api_yz.prd]XXCK
Jun 17 11:46:55 iZ23pw03glwZ log.txt:  [fusion0_api_yz.prd]<type 'exceptions.IndexError'>
Jun 17 11:46:55 iZ23pw03glwZ log.txt:  list index out of range
Jun 17 11:46:55 iZ23pw03glwZ log.txt:  [('/usr/local/lib/python2.7/

**Comment by jonahfang** [comment]
File "./apps/voucher/exports/abstract_voucher.py", line 355, in init
Jun 20 08:53:25 iZ23pw03glwZ log.txt:      added_who=self.user_full_name)
IntegrityError: (1062, "Duplicate entry '51-1-1001' for key 'user_id'")
