### ISSUE TITLE
发货完成时出错

### ISSUE THREAD

**Issue by jonahfang** [jonahfang/yzcycnproject#402]
```
[fusion0_api_yz.prd]EVENT:POST:完成发货,USER:101-薛霞
[fusion0_api_yz.prd]Internal Server Error: /psstock/myshiping/done
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "./apps/utils/common/common_require.py", line 18, in _closure
    return func(request, *args, **kwargs)
  File "./apps/utils/common/common_require.py", line 131, in _closure
    return func(request, *args, **kwargs)
  File "./apps/utils/common/common_require.py", line 92, in _closure
    return func(request, *args, **kwargs)
  File "./apps/utils/log.py", line 43, in _closure
    return func(request, *args, **kwargs)
  File "./apps/ps_stock/views/ship/shiping.py", line 59, in complete_my_shiping
    company_buy_group_name = new_obj['companyBuyGroupName']
KeyError: 'companyBuyGroupName'
```

**Comment by jonahfang** [comment]
已做了预防性编程，原因不明。
