### ISSUE TITLE
某些餐厅（如百丈）无法选择商品（录入订单时），总部操作又是好的

### ISSUE THREAD

**Issue by jonahfang** [jonahfang/yzcycnproject#77]
后台错误信息：
Feb 20 14:51:21 iZ23pw03glwZ log.txt:  [('/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py', 113, 'get_response', 'response = callback(request, *callback_args, **callback_kwargs)'), ('./apps/myapiproxy/views/proxy.py', 39, 'handle_api_call', 'r = requests.get(target_url)'), ('/usr/local/lib/python2.7/dist-packages/requests/api.py', 69, 'get', "return request('get', url, params=params, **kwargs)"), ('/usr/local/lib/python2.7/dist-packages/requests/api.py', 50, 'request', 'response = session.request(method=method, url=url, **kwargs)'), ('/usr/local/lib/python2.7/dist-packages/requests/sessions.py', 468, 'request', 'resp = self.send(prep, **send_kwargs)'), ('/usr/local/lib/python2.7/dist-packages/requests/sessions.py', 576, 'send', 'r = adapter.send(request, **kwargs)'), ('/usr/local/lib/python2.7/dist-packages/requests/adapters.py', 423, 'send', 'raise ConnectionError(e, request=request)')]
Feb 20 14:51:21 iZ23pw03glwZ log.txt:  [fusion0web.yz][2016-02-20 Sat 14:51:20] ERROR [django.request:210] Internal Server Error: /myapi/psbasedata/goods/searchresults
Feb 20 14:51:21 iZ23pw03glwZ log.txt:  Traceback (most recent call last):
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      response = callback(request, *callback_args, **callback_kwargs)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "./apps/myapiproxy/views/proxy.py", line 39, in handle_api_call
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      r = requests.get(target_url)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      return request('get', url, params=params, **kwargs)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      response = session.request(method=method, url=url, **kwargs)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      resp = self.send(prep, **send_kwargs)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      r = adapter.send(request, **kwargs)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
Feb 20 14:51:21 iZ23pw03glwZ log.txt:      raise ConnectionError(e, request=request)
Feb 20 14:51:21 iZ23pw03glwZ log.txt:  ConnectionError: HTTPConnectionPool(host='yzapi', port=80): Max retries exceeded with url: /psbasedata/goods/searchresults?_dc=1455950930145&query=xiqi&auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NTYwMDg2NTUsIm5hbWUiOiJCWiIsInJvbGVzIjoicHMub3JkZXIscHMuZGQiLCJuYmYiOjE0NTU5MjIyNTUsImZ1bGxfbmFtZSI6Ilx1NzY3ZVx1NGUwOCIsImRlcHRfaWQiOjEsImlhdCI6MTQ1NTkyMjI1NSwiaWQiOjUzfQ.ElC41wca9fuqh-Nw51dUnnS6DWGhrgeX7hcxU-DlD40 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f2914b304d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by jonahfang** [comment]
中文输入法改进后，问题解决。
