### ISSUE TITLE
订单录入时会报错

### ISSUE THREAD

**Issue by jonahfang** [jonahfang/yzcycnproject#78]
错误信息如下:

```
Feb 21 08:00:04 iZ23pw03glwZ log.txt:  [fusion0_api_yz][2016-02-21 Sun 08:00:04] ERROR [django.request:210] Internal Server Error: /voucher/vouchercatcodes/0302/booking
Feb 21 08:00:04 iZ23pw03glwZ log.txt:  Traceback (most recent call last):
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      response = callback(request, *callback_args, **callback_kwargs)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/utils/common/common_require.py", line 18, in _closure
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      return func(request, *args, **kwargs)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/utils/common/common_require.py", line 131, in _closure
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      return func(request, *args, **kwargs)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/utils/log.py", line 42, in _closure
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      return func(request, *args, **kwargs)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/voucher/views/voucher_booking.py", line 56, in get_or_add_or_delete_voucher_booking
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      return obj.add(new_obj)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/ps_order/views/voucher/voucher_0302.py", line 71, in add
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      voucher_booking_obj = self.get_booking_voucher_obj(page_number)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "./apps/voucher/exports/abstract_voucher.py", line 564, in get_booking_voucher_obj
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      page_number=page_number)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      return self.get_query_set().get(*args, **kwargs)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
Feb 21 08:00:04 iZ23pw03glwZ log.txt:      self.model._meta.object_name)
Feb 21 08:00:04 iZ23pw03glwZ log.txt:  DoesNotExist: VoucherBooking matching query does not exist.

```

**Comment by jonahfang** [comment]
怀疑是用户重复按了两次保存按钮，现在程序改进后，出现提示信息“正在保存，请稍候”，并能禁止重复按键。
